Repository rsksmart/rLogin, pull requests merged in 2020-11, with the labels that each got.

#12 EIP 1193 support
  README.md
  package-lock.json
  package.json
  sample/back/index.js
  sample/decentralized/README.md
  sample/decentralized/index.html
  sample/front/favicon.ico
  sample/front/index.html
  sample/launcher.js
  sample/with_be/README.md
  sample/with_be/front/favicon.ico
  sample/with_be/front/index.html
  src/RLogin.tsx
  src/adapters.ts
  src/components/Core.test.tsx
  src/components/Core.tsx
  src/components/shared/ErrorMessage.test.tsx
  src/components/shared/ErrorMessage.tsx
  src/components/step1/WalletProviders.test.tsx
  src/constants/cssSelectors.ts
  src/constants/events.ts
  src/images/ErrorCircle.tsx
  src/index.ts
Labels: documentation, enhancement, standard, ui

#17 Nifty wallet support
  package.json
  sample/front/index.html
  src/components/Core.tsx
Labels: enhancement

#19 LGTM fixes
  package.json
  src/components/Core.tsx
  webpack.config.js
Labels: bug

#21 Fix sample app networks
  sample/front/index.html
Labels: bug

#24 Add DID Auth support
  package-lock.json
  package.json
  sample/back/index.js
  sample/front/index.html
  src/components/Core.tsx
  src/constants.ts
  src/index.ts
Labels: back-end, enhancement, standard

#30 Remove autoRefreshOnNetworkChange
  README.md
  sample/front/index.html
Labels: bug, documentation
